import { Jobpostings } from "./jobpostings";
import { Jobseeker } from "./jobseeker";
import { Resume } from "./resume";

export interface Application {
  applicationId?: number; // Optional, generated by the backend
  jobPosting_id: number;  // ID of the job being applied for
  jobSeeker_id: number;   // ID of the job seeker
  resume_id: number;      // ID of the resume
  status?: string;        // Optional, e.g., 'Pending'
  appliedAt?: Date;       // Optional, backend sets the timestamp

  jobPosting?: Jobpostings;   // Job posting details
  jobSeeker?: Jobseeker;     // Job seeker details
  resume?: Resume;  
}